//import data type from next
import type { Metadata } from "next";

//import global style
import "./globals.css";

//import ChakraUI Providers
import { Providers } from "./chakraui.providers";

//import reusable components
import { LayoutContainer, Navbar } from "@/components";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <Providers>
          <LayoutContainer>
            <Navbar />
            {children}
          </LayoutContainer>
        </Providers>
      </body>
    </html>
  );
}
